security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User\User
                property: email

    role_hierarchy:
        ROLE_TEST_1: ROLE_USER
        ROLE_TEST_2: ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_IMPERSONATE ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            context: user
            pattern: /admin(.*)
            custom_authenticator:
                - App\Security\Admin\AdminAuthenticator
            user_checker: App\Security\Admin\AdminChecker
            form_login:
                provider: app_user_provider
                login_path: admin_login
                use_forward: false
                check_path: admin_login
                failure_path: null
            entry_point: form_login
            logout:
                path: admin_logout
                target: admin_login
            switch_user: { role: ROLE_IMPERSONATE }
            remember_me:
                secret: '%kernel.secret%' # required
                lifetime: 2419200 # 1 month in seconds
                signature_properties: [ 'password', 'email' ]

        main:
            context: user
            pattern: .*
            custom_authenticator:
                - App\Security\Main\MainAuthenticator
            user_checker: App\Security\Main\MainChecker
            form_login:
                provider: app_user_provider
                login_path: login
                use_forward: false
                check_path: login
                failure_path: null
            entry_point: form_login
            logout:
                path: logout
                target: login
            switch_user: { role: ROLE_IMPERSONATE }
            remember_me:
                secret: '%kernel.secret%' # required
                lifetime: 2419200 # 1 month in seconds
                signature_properties: [ 'password', 'email' ]

    access_control:
        # Admin config
        - { path: ^/admin/login$, role: PUBLIC_ACCESS }
        - { path: ^/admin/logout$, role: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }

        # Main config
        - { path: ^/.*, role: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
