sonata_admin:
    title: 'Administration'
    title_logo: '/app_icon/icon_100px.png'

    security:
        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN

    dashboard:
        groups:
            group:
                on_top: true
                label: Utilisateurs
                icon: '<i class="fa fa-users"></i>'
                items:
                    - admin.user

    assets:
        extra_javascripts:
#            - exemple.js

        extra_stylesheets:
#            - exemple.css

    breadcrumbs:
        child_admin_route: edit

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
