parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

# Admin Part
    admin.user:
        class: App\Admin\UserAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\User\User, controller: ~, manager_type: orm, group: admin, label: User }
        calls:
            - [ setUserPasswordHasher, [ '@security.user_password_hasher' ] ]
            - [ setTranslationDomain, [ 'UserAdmin' ] ]